code --install-extension 2gua.rainbow-brackets
code --install-extension andrewmarkle.primer-light
code --install-extension Angular.ng-template
code --install-extension ardenivanov.svelte-intellisense
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bernik.theme-codeschool2-minimal
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-mermaid
code --install-extension cometeer.spacemacs
code --install-extension Compulim.vscode-clock
code --install-extension dbaeumer.vscode-eslint
code --install-extension dendron.dendron
code --install-extension dendron.dendron-markdown-links
code --install-extension dendron.dendron-markdown-notes
code --install-extension dendron.dendron-markdown-preview-enhanced
code --install-extension dendron.dendron-markdown-shortcuts
code --install-extension dendron.dendron-paste-image
code --install-extension dendron.dendron-snippet-maker
code --install-extension dermohamad.ayu-owl
code --install-extension DiryoX.Paper-tmTheme
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension ethansugar.monokai-light
code --install-extension foolusion.acme-theme
code --install-extension formulahendry.code-runner
code --install-extension gerane.Theme-Blackboard
code --install-extension gerane.Theme-Chelevra
code --install-extension golang.go
code --install-extension Gruntfuggly.activitusbar
code --install-extension Gruntfuggly.todo-tree
code --install-extension idbartosz.darkpp-italic
code --install-extension James-Yu.latex-workshop
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension kortina.vscode-markdown-notes
code --install-extension kosz78.nim
code --install-extension liviuschera.noctis
code --install-extension mattn.Lisp
code --install-extension mervin.markdown-formatter
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-themes
code --install-extension mushan.vscode-paste-image
code --install-extension obrejla.netbeans-light-theme
code --install-extension philipbe.theme-gray-matter
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension redhat.java
code --install-extension richie5um2.vscode-sort-json
code --install-extension RomanPeshkov.vscode-text-tables
code --install-extension sabertazimi.latex-snippets
code --install-extension samuelcolvin.jinjahtml
code --install-extension sdras.night-owl
code --install-extension sissel.shopify-liquid
code --install-extension steoates.autoimport
code --install-extension strangerelics.clarity-light
code --install-extension supudonet.supudo-light
code --install-extension teabyii.ayu
code --install-extension thedavej.night-owl-black
code --install-extension tootone.org-mode
code --install-extension urld.nofrills
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension webhint.vscode-webhint
code --install-extension wesbos.theme-cobalt2
code --install-extension XephAlpha.syntax
code --install-extension yzhang.markdown-all-in-one
